###
{{redmineurl}}/issues.json
X-Redmine-API-Key: {{redminekey}}
### 
{{redmineurl}}/issues/1.json?include=journals
X-Redmine-API-Key: {{redminekey}}

### 
{{redmineurl}}/enumerations/issue_priorities.json
X-Redmine-API-Key: {{redminekey}}
